version: "3.9"
services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./server
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    env_file:
      - ./server/.env

  frontend:
    build: ./Frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

  admin:
    build: ./admin
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mongo-data: